#!/usr/bin/env python
#%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%#
#%!%!% ------------------------------- ElaStic_Setup_WIEN2k -------------------------------- %!%!%#
#%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%#
#
# AUTHOR:
# Rostam Golesorkhtabar
# r.golesorkhtabar@gmail.com
# 
# DATE:
# Sun Jan 01 00:00:00 2012
#
# SYNTAX:
# python ElaStic_Setup_WIEN2k.py
#        ElaStic_Setup_WIEN2k
# 
# EXPLANATION:
# 
#__________________________________________________________________________________________________

from sys   import stdin
from numpy import *
from math  import *
import numpy as np
import os.path
import shutil
import glob
import math
import sys
import os

#%!%!%--- DICTIONARIS ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!
Ls_Dic={                       \
'01':[ 1., 1., 1., 0., 0., 0.],\
'02':[ 1., 0., 0., 0., 0., 0.],\
'03':[ 0., 1., 0., 0., 0., 0.],\
'04':[ 0., 0., 1., 0., 0., 0.],\
'05':[ 0., 0., 0., 2., 0., 0.],\
'06':[ 0., 0., 0., 0., 2., 0.],\
'07':[ 0., 0., 0., 0., 0., 2.],\
'08':[ 1., 1., 0., 0., 0., 0.],\
'09':[ 1., 0., 1., 0., 0., 0.],\
'10':[ 1., 0., 0., 2., 0., 0.],\
'11':[ 1., 0., 0., 0., 2., 0.],\
'12':[ 1., 0., 0., 0., 0., 2.],\
'13':[ 0., 1., 1., 0., 0., 0.],\
'14':[ 0., 1., 0., 2., 0., 0.],\
'15':[ 0., 1., 0., 0., 2., 0.],\
'16':[ 0., 1., 0., 0., 0., 2.],\
'17':[ 0., 0., 1., 2., 0., 0.],\
'18':[ 0., 0., 1., 0., 2., 0.],\
'19':[ 0., 0., 1., 0., 0., 2.],\
'20':[ 0., 0., 0., 2., 2., 0.],\
'21':[ 0., 0., 0., 2., 0., 2.],\
'22':[ 0., 0., 0., 0., 2., 2.],\
'23':[ 0., 0., 0., 2., 2., 2.],\
'24':[-1., .5, .5, 0., 0., 0.],\
'25':[ .5,-1., .5, 0., 0., 0.],\
'26':[ .5, .5,-1., 0., 0., 0.],\
'27':[ 1.,-1., 0., 0., 0., 0.],\
'28':[ 1.,-1., 0., 0., 0., 2.],\
'29':[ 0., 1.,-1., 0., 0., 2.],\
'30':[ .5, .5,-1., 0., 0., 2.],\
'31':[ 1., 0., 0., 2., 2., 0.],\
'32':[ 1., 1.,-1., 0., 0., 0.],\
'33':[ 1., 1., 1.,-2.,-2.,-2.],\
'34':[ .5, .5,-1., 2., 2., 2.],\
'35':[ 0., 0., 0., 2., 2., 4.],\
'36':[ 1., 2., 3., 4., 5., 6.],\
'37':[-2., 1., 4.,-3., 6.,-5.],\
'38':[ 3.,-5.,-1., 6., 2.,-4.],\
'39':[-4.,-6., 5., 1.,-3., 2.],\
'40':[ 5., 4., 6.,-2.,-1.,-3.],\
'41':[-6., 3.,-2., 5.,-4., 1.]}

Ls_str={                                     \
'01':'(  eta,  eta,  eta,  0.0,  0.0,  0.0)',\
'02':'(  eta,  0.0,  0.0,  0.0,  0.0,  0.0)',\
'03':'(  0.0,  eta,  0.0,  0.0,  0.0,  0.0)',\
'04':'(  0.0,  0.0,  eta,  0.0,  0.0,  0.0)',\
'05':'(  0.0,  0.0,  0.0, 2eta,  0.0,  0.0)',\
'06':'(  0.0,  0.0,  0.0,  0.0, 2eta,  0.0)',\
'07':'(  0.0,  0.0,  0.0,  0.0,  0.0, 2eta)',\
'08':'(  eta,  eta,  0.0,  0.0,  0.0,  0.0)',\
'09':'(  eta,  0.0,  eta,  0.0,  0.0,  0.0)',\
'10':'(  eta,  0.0,  0.0, 2eta,  0.0,  0.0)',\
'11':'(  eta,  0.0,  0.0,  0.0, 2eta,  0.0)',\
'12':'(  eta,  0.0,  0.0,  0.0,  0.0, 2eta)',\
'13':'(  0.0,  eta,  eta,  0.0,  0.0,  0.0)',\
'14':'(  0.0,  eta,  0.0, 2eta,  0.0,  0.0)',\
'15':'(  0.0,  eta,  0.0,  0.0, 2eta,  0.0)',\
'16':'(  0.0,  eta,  0.0,  0.0,  0.0, 2eta)',\
'17':'(  0.0,  0.0,  eta, 2eta,  0.0,  0.0)',\
'18':'(  0.0,  0.0,  eta,  0.0, 2eta,  0.0)',\
'19':'(  0.0,  0.0,  eta,  0.0,  0.0, 2eta)',\
'20':'(  0.0,  0.0,  0.0, 2eta, 2eta,  0.0)',\
'21':'(  0.0,  0.0,  0.0, 2eta,  0.0, 2eta)',\
'22':'(  0.0,  0.0,  0.0,  0.0, 2eta, 2eta)',\
'23':'(  0.0,  0.0,  0.0, 2eta, 2eta, 2eta)',\
'24':'( -eta,.5eta,.5eta,  0.0,  0.0,  0.0)',\
'25':'(.5eta, -eta,.5eta,  0.0,  0.0,  0.0)',\
'26':'(.5eta,.5eta, -eta,  0.0,  0.0,  0.0)',\
'27':'(  eta, -eta,  0.0,  0.0,  0.0,  0.0)',\
'28':'(  eta, -eta,  0.0,  0.0,  0.0, 2eta)',\
'29':'(  0.0,  eta, -eta,  0.0,  0.0, 2eta)',\
'30':'(.5eta,.5eta, -eta,  0.0,  0.0, 2eta)',\
'31':'(  eta,  0.0,  0.0, 2eta, 2eta,  0.0)',\
'32':'(  eta,  eta, -eta,  0.0,  0.0,  0.0)',\
'33':'(  eta,  eta,  eta,-2eta,-2eta,-2eta)',\
'34':'(.5eta,.5eta, -eta, 2eta, 2eta, 2eta)',\
'35':'(  0.0,  0.0,  0.0, 2eta, 2eta, 4eta)',\
'36':'( 1eta, 2eta, 3eta, 4eta, 5eta, 6eta)',\
'37':'(-2eta, 1eta, 4eta,-3eta, 6eta,-5eta)',\
'38':'( 3eta,-5eta,-1eta, 6eta, 2eta,-4eta)',\
'39':'(-4eta,-6eta, 5eta, 1eta,-3eta, 2eta)',\
'40':'( 5eta, 4eta, 6eta,-2eta,-1eta,-3eta)',\
'41':'(-6eta, 3eta,-2eta, 5eta,-4eta, 1eta)'}

LC_Dic = {              \
'CI' :'Cubic I'        ,\
'CII':'Cubic II'       ,\
'HI' :'Hexagonal I'    ,\
'HII':'Hexagonal II'   ,\
'RI' :'Rhombohedral I' ,\
'RII':'Rhombohedral II',\
'TI' :'Tetragonal I'   ,\
'TII':'Tetragonal II'  ,\
'O'  :'Orthorhombic'   ,\
'M'  :'Monoclinic'     ,\
'N'  :'Triclinic'} 
#--------------------------------------------------------------------------------------------------

#%!%!%--- Reading the method of the elastic constants calculations ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%
print '\n     Energy  ---=>  1    \
       \n     Stress  ---=>  2    '
num = input('>>>> Please choose the method of the calculation (choose 1 or 2): ')
if (num != 1 and num != 2):
    sys.exit("\n.... Oops ERROR: Choose '1' or '2' \n")
if (num == 1 ): mthd = 'Energy'
if (num == 2 ): mthd = 'Stress'
#--------------------------------------------------------------------------------------------------

#%!%!%--- Reading the order of the elastic constants ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%
print '\n     2nd  ---=>  2    \
       \n     3rd  ---=>  3    '
ordr = input('>>>> Please choose the order of the elastic constant (choose 2 or 3): ')
if (ordr != 2 and ordr != 3 ):
    sys.exit("\n.... Oops ERROR: Choose '2' or '3' \n")
#--------------------------------------------------------------------------------------------------

#%!%!%--- Checking the case.struct file exist ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!
path       = os.getcwd()
dir_name   = os.path.basename(path)
case_struct= dir_name+'.struct'
if (os.path.exists(case_struct) == False):
    sys.exit('\n.... Oops ERROR: There is NO '+ case_struct +' file !?!?!?\n')
#--------------------------------------------------------------------------------------------------

#%!%!%--- Calculating the Space-Group Number and classifying it ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!
os.system('x sgroup')
sgroup_out = dir_name+'.outputsgroup'

SGf   = open(sgroup_out, 'r')
SGlins= SGf.readlines()
SGf.close()

if (SGlins[0].find('warning') >= 0): 
    sys.exit('\n.... Oops WARNING: There is a warning in "'+ sgroup_out +'" file !?!?!?\n')

for i in range(len(SGlins)):
    if (SGlins[i].find('Number and name of space group:') >= 0):
        SGN = int(float(SGlins[i].split()[6]))
        SGN_explanation=SGlins[i].strip()
        break

if (1 <= SGN and SGN <= 2):      # Triclinic
    LC = 'N'
    if (ordr == 2): ECs = 21
    if (ordr == 3): ECs = 56

elif(3 <= SGN and SGN <= 15):    # Monoclinic
    LC = 'M'
    if (ordr == 2): ECs = 13
    if (ordr == 3): ECs = 32

elif(16 <= SGN and SGN <= 74):   # Orthorhombic
    LC = 'O'
    if (ordr == 2): ECs =  9
    if (ordr == 3): ECs = 20

elif(75 <= SGN and SGN <= 88):   # Tetragonal II
    LC = 'TII'
    if (ordr == 2): ECs =  7
    if (ordr == 3): ECs = 16
  
elif(89 <= SGN and SGN <= 142):  # Tetragonal I
    LC = 'TI'
    if (ordr == 2): ECs =  6
    if (ordr == 3): ECs = 12

elif(143 <= SGN and SGN <= 148): # Rhombohedral II 
    LC = 'RII'
    if (ordr == 2): ECs =  7
    if (ordr == 3): ECs = 20

elif(149 <= SGN and SGN <= 167): # Rhombohedral I
    LC = 'RI'
    if (ordr == 2): ECs =  6
    if (ordr == 3): ECs = 14

elif(168 <= SGN and SGN <= 176): # Hexagonal II
    LC = 'HII'
    if (ordr == 2): ECs =  5
    if (ordr == 3): ECs = 12

elif(177 <= SGN and SGN <= 194): # Hexagonal I
    LC = 'HI'
    if (ordr == 2): ECs =  5
    if (ordr == 3): ECs = 10

elif(195 <= SGN and SGN <= 206): # Cubic II
    LC = 'CII'
    if (ordr == 2): ECs =  3
    if (ordr == 3): ECs =  8

elif(207 <= SGN and SGN <= 230): # Cubic I
    LC = 'CI'
    if (ordr == 2): ECs =  3
    if (ordr == 3): ECs =  6
else: sys.exit('\n.... Oops ERROR: WRONG Space-Group Number !?!?!?    \n')

if (ordr == 2): order = 'second'
if (ordr == 3): order = 'third'
print '\n     '+ SGN_explanation +'\
       \n     '+ LC_Dic[LC] +' structure in the Laue classification.\
       \n     This structure has '+ str(ECs) +' independent '+ order +'-order elastic constants.'

os.system('rm -f :log *outputsgroup* *struct_sgroup')
#--------------------------------------------------------------------------------------------------

#%!%!%--- Reading the case.struct file ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%
INF   = open(case_struct,'r')
lines = INF.readlines()
title = lines[0][ 0:80].strip()
Ltype = lines[1][ 0: 3].strip()
mode  = lines[2][13:17].strip()
unit  = lines[2][23:27].strip()
NAT_L = int(lines[1][27:30])

if (Ltype!='P'   and \
    Ltype!='B'   and \
    Ltype!='F'   and \
    Ltype!='H'   and \
    Ltype!='R'   and \
    Ltype!='CXY' and \
    Ltype!='CXZ'):
    sys.exit('\n.... Oops ERROR: WRONG lattice type, Check the "'+ case_struct +'" file !?!?!?\n')

a1    = float(lines[3][ 0:10])
a2    = float(lines[3][10:20])
a3    = float(lines[3][20:30])
alpha = float(lines[3][30:40])
beta  = float(lines[3][40:50])
gamma = float(lines[3][50:60])

if (Ltype == 'H'): 
    gamma  = 120.0
    Ltype  = 'P'
 
if (Ltype == 'R'):
    a_R    = sqrt((a3**2.)/9. + (a1**2.)/3.)
    alpha_R= 2.*asin(a1/(2.*a_R))
    a1     = a_R
    a2     = a_R
    a3     = a_R
    alpha  = degrees(alpha_R)
    beta   = degrees(alpha_R)
    gamma  = degrees(alpha_R)
    Ltype  = 'P'

dummy1 = []
for line in lines:
    if (line.find('MULT=') >= 0): 
        l     = line
        MULT  = int(l[15:17])
        ISPLIT= int(l[34:36])
        dummy1.append([MULT, ISPLIT])

dummy2 = []
for line in lines:
    if (line.find('NPT=') >= 0):
        l     = line
        Aname = l[0:10]
        NPT   = float(l[15:20])
        R0    = float(l[25:35])
        RMT   = float(l[40:50])
        Z     = float(l[55:60])
        dummy2.append([Aname, NPT, R0, RMT, Z])

dummy3 = []
nl     = -1
for line in lines:
    nl += 1
    if (line.find('LOCAL ROT MATRIX:    ') >= 0):
        rotm1 = lines[nl+0][20:41] + lines[nl+0][41:51].strip()
        rotm2 = lines[nl+1][20:41] + lines[nl+1][41:51].strip()
        rotm3 = lines[nl+2][20:41] + lines[nl+2][41:51].strip()
        dummy3.append([rotm1, rotm2, rotm3])

INFO_L = []
for i in range(NAT_L):
    INFO_L.append(dummy1[i] + dummy2[i] + dummy3[i])

POSN_L = []
for line in lines:
    if (line.find('X=') >= 0):
        l = line
        X = float(l[12:22])
        Y = float(l[25:35])
        Z = float(l[38:48])
        POSN_L.append([X, Y, Z])

INF.close()
#--------------------------------------------------------------------------------------------------

#%!%!%--- Preparing the atomic positions of the primitive cell ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%
if (Ltype == 'P'  ): NAT_P = NAT_L*1
if (Ltype == 'B'  ): NAT_P = NAT_L*2
if (Ltype == 'F'  ): NAT_P = NAT_L*4
if (Ltype == 'CXY'): NAT_P = NAT_L*2
if (Ltype == 'CXZ'): NAT_P = NAT_L*2

bgn    = 0
infl   = []
INFO_P = []
POSN_P = []
for i in range(NAT_L):
    infl = INFO_L[i]
    numa = INFO_L[i][0]
    end  = bgn + numa
    posl = []
    for j in range(bgn, end):
        posl.append(POSN_L[j])
    bgn = end

    if (Ltype == 'P'):
        T = [[.0, .0, .0]]
    if (Ltype == 'B'):
        T = [[.0, .0, .0],
             [.5, .5, .5]]
    if (Ltype == 'F'):
        T = [[.0, .0, .0],
             [.5, .5, .0],
             [.5, .0, .5],
             [.0, .5, .5]]
    if (Ltype == 'CXY'):
        T = [[.0, .0, .0],
             [.5, .5, .0]]
    if (Ltype == 'CXZ'):
        T = [[.0, .0, .0],
             [.5, .0, .5]]

    for j in range(len(T)):
        INFO_P.append(infl)
        for k in range(len(posl)):
            POSN_P.append([(T[j][0]+posl[k][0])%1, (T[j][1]+posl[k][1])%1, (T[j][2]+posl[k][2])%1])
#--------------------------------------------------------------------------------------------------

#%!%!%--- Writing the case_P.struct file ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%
fP = open(dir_name+'_P.struct', 'w')
print>>fP, title
print>>fP, 'P   LATTICE,NONEQUIV.ATOMS:'+'%3d'%(NAT_P)
print>>fP, 'MODE OF CALC='+mode+' unit='+unit
print>>fP, '%10.6f'%(a1)   + \
           '%10.6f'%(a2)   + \
           '%10.6f'%(a3)   + \
           '%10.6f'%(alpha)+ \
           '%10.6f'%(beta) + \
           '%10.6f'%(gamma)

if (LC == 'CI' or\
    LC == 'CII'):
    index = ' '
else:
    index = '-'

bgn = 0
for i in range(len(INFO_P)):
    if ( 1 <= i+1 and i+1 <=   9): atom_index ='  '+index+str(i+1)
    if (10 <= i+1 and i+1 <=  99): atom_index = ' '+index+str(i+1)
    if (99 <= i+1 and i+1 <= 999): atom_index =     index+str(i+1)

    numa= INFO_P[i][0]
    end = bgn + numa
    for j in range(bgn, end):
        print>>fP, 'ATOM'+atom_index+': X='+'%10.8f'%(POSN_P[j][0]) + \
                                      ' Y='+'%10.8f'%(POSN_P[j][1]) + \
                                      ' Z='+'%10.8f'%(POSN_P[j][2])
        if (j == bgn): print>>fP, '          MULT='  +'%2d'%(INFO_P[i][0]) + \
                                  '          ISPLIT='+'%2d'%(INFO_P[i][1])
    bgn = end

    print>>fP, INFO_P[i][2]+' NPT='+'%5d'   %(INFO_P[i][3]) + \
                            '  R0='+'%10.8f'%(INFO_P[i][4]) + \
                            ' RMT='+'%10.5f'%(INFO_P[i][5]) + \
                            '   Z:'+'%7.2f' %(INFO_P[i][6])
    print>>fP, 'LOCAL ROT MATRIX:   '+INFO_P[i][7]
    print>>fP, '                    '+INFO_P[i][8]
    print>>fP, '                    '+INFO_P[i][9]
print>>fP, '   0      NUMBER OF SYMMETRY OPERATIONS'
fP.close()
#--------------------------------------------------------------------------------------------------

#%!%!%--- Reading the maximum Lagrangian strain ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!
if (mthd == 'Energy'):
    mdr = input('\n>>>> Please enter the maximum Lagrangian strain '\
                '\n     The suggested value is between 0.030 and 0.150: ')
if (mthd == 'Stress'):
    mdr = input('\n>>>> Please enter the maximum Lagrangian strain '\
                '\n     The suggested value is between 0.0010 and 0.0050: ')

if (1 < mdr or mdr < 0):
    sys.exit('\n.... Oops ERROR: The maximum Lagrangian strain is out of range !!!!!!\n')

mdr = round(mdr, 3)
print '     The maximum Lagrangian strain is '+ str(mdr) + '\n'
#--------------------------------------------------------------------------------------------------

#%!%!%--- Reading the number of the distorted structures ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%
NoP = input('>>>> Please enter the number of the distorted structures [odd number > 4]: ')
NoP = int(abs(NoP))

if (NoP < 5):
    sys.exit('\n.... Oops ERROR: The NUMBER of the distorted structures < 5 !!!!!!    \n')
if (99 < NoP):
    sys.exit('\n.... Oops ERROR: The NUMBER of the distorted structures > 99 !!!!!!   \n')

if (NoP%2 == 0):
    NoP   += 1
print '     The number of the distorted structures is '+ str(NoP) + '\n'

ptn = int((NoP-1)/2)

if (mthd == 'Energy'): interval = 0.0001
if (mthd == 'Stress'): interval = 0.00001

if (mdr/ptn <= interval):
    sys.exit('.... Oops ERROR: The interval of the strain values is < '+ str(interval) +\
           '\n                 Choose a larger maximum Lagrangian strain'\
           '\n                 or a less number of distorted structures.\n')
#--------------------------------------------------------------------------------------------------

#%!%!%--- Making the M_old matrix ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!
alpha = radians(alpha)
beta  = radians(beta)
gamma = radians(gamma)

M_old = zeros((3,3))

if (LC == 'CI'  or \
    LC == 'CII' or \
    LC == 'TI'  or \
    LC == 'TII' or \
    LC == 'O'):

    M_old[0,0] = a1
    M_old[0,1] = 0.
    M_old[0,2] = 0.

    M_old[1,0] = 0.
    M_old[1,1] = a2
    M_old[1,2] = 0.

    M_old[2,0] = 0.
    M_old[2,1] = 0.
    M_old[2,2] = a3


if (LC == 'HI' or \
    LC == 'HII'):

    M_old[0,0] = a1
    M_old[0,1] = 0.
    M_old[0,2] = 0.

    M_old[1,0] =-a2/2.
    M_old[1,1] = a2*sqrt(3.)/2.
    M_old[1,2] = 0.

    M_old[2,0] = 0.
    M_old[2,1] = 0.
    M_old[2,2] = a3


if (LC == 'RI' or \
    LC == 'RII'):
    if (SGN == 146 or \
        SGN == 148 or \
        SGN == 155 or \
        SGN == 160 or \
        SGN == 161 or \
        SGN == 166 or \
        SGN == 167 ):

        M_old[0,0] = a1*sin(alpha/2.)
        M_old[0,1] =-a1*sin(alpha/2.)/sqrt(3.)
        M_old[0,2] = a1*sqrt(1.-(4./3.*(sin(alpha/2.))**2.))

        M_old[1,0] = 0.
        M_old[1,1] =-M_old[0,1]*2.
        M_old[1,2] = M_old[0,2]

        M_old[2,0] =-M_old[0,0]
        M_old[2,1] = M_old[0,1]
        M_old[2,2] = M_old[0,2]

    else:
        M_old[0,0] = a1
        M_old[0,1] = 0.
        M_old[0,2] = 0.

        M_old[1,0] =-a2/2.
        M_old[1,1] = a2*sqrt(3.)/2.
        M_old[1,2] = 0.

        M_old[2,0] = 0.
        M_old[2,1] = 0.
        M_old[2,2] = a3


if (LC == 'M'):
    M_old[0,0] = a1*sin(gamma)
    M_old[0,1] = a1*cos(gamma)
    M_old[0,2] = 0.

    M_old[1,0] = 0.
    M_old[1,1] = a2
    M_old[1,2] = 0.

    M_old[2,0] = 0.
    M_old[2,1] = 0.
    M_old[2,2] = a3


if (LC == 'N'):
    M_old[0,0] = a1
    M_old[0,1] = 0.
    M_old[0,2] = 0.

    M_old[1,0] = a2*cos(gamma)
    M_old[1,1] = a2*sin(gamma)
    M_old[1,2] = 0.  

    M_old[2,0] = a3*cos(beta)
    M_old[2,1] =(a3*(cos(alpha)-cos(beta)*cos(gamma)))/sin(gamma)    
    M_old[2,2] = a3*sqrt(1.-(cos(alpha))**2.-(cos(beta))**2.-(cos(gamma))**2. \
               + 2.*cos(alpha)*cos(beta)*cos(gamma))/sin(gamma)

D = np.linalg.det(M_old)
if (Ltype == 'P'  ): V0 = D/1.
if (Ltype == 'B'  ): V0 = D/2.
if (Ltype == 'F'  ): V0 = D/4.
if (Ltype == 'CXY'): V0 = D/2.
if (Ltype == 'CXZ'): V0 = D/2.

#%!%!%--- Writing the "INFO_ElaStic" file ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!
INFO = open('INFO_ElaStic','w')
print >>INFO, 'Order of elastic constants      =', ordr         ,\
            '\nMethod of calculation           =', mthd         ,\
            '\nDFT code name                   = WIEN2k'        ,\
            '\nSpace-group number              =', SGN          ,\
            '\nVolume of equilibrium unit cell =', V0, '[a.u^3]',\
            '\nMaximum Lagrangian strain       =', mdr          ,\
            '\nNumber of distorted structures  =', NoP
INFO.close()
#--------------------------------------------------------------------------------------------------

#%!%!%--- Directory Management ---%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%
OLDlist = glob.glob('Dst??_old')
for Dstn_old in OLDlist:
    shutil.rmtree(Dstn_old)

Dstlist = glob.glob('Dst??')
for Dstn in Dstlist:
    os.rename(Dstn, Dstn+'_old')

if (os.path.exists('Structures_WIEN2k_old')):
    shutil.rmtree( 'Structures_WIEN2k_old')

if (os.path.exists('Structures_WIEN2k')):
    os.rename(     'Structures_WIEN2k', 'Structures_WIEN2k_old')
#--------------------------------------------------------------------------------------------------

if (mthd == 'Energy'):
    if (ordr == 2):
        if (LC == 'CI' or \
            LC == 'CII'):
            Lag_strain_list = ['01','08','23']
        if (LC == 'HI' or \
            LC == 'HII'):
            Lag_strain_list = ['01','26','04','03','17']
        if (LC == 'RI'):
            Lag_strain_list = ['01','08','04','02','05','10']
        if (LC == 'RII'):
            Lag_strain_list = ['01','08','04','02','05','10','11']
        if (LC == 'TI'):
            Lag_strain_list = ['01','26','27','04','05','07']
        if (LC == 'TII'):
            Lag_strain_list = ['01','26','27','28','04','05','07']
        if (LC == 'O'):
            Lag_strain_list = ['01','26','25','27','03','04','05','06','07']
        if (LC == 'M'):
            Lag_strain_list = ['01','25','24','28','29','27','20','12','03','04','05','06','07']
        if (LC == 'N'):
            Lag_strain_list = ['02','03','04','05','06','07','08','09','10','11',\
                               '12','13','14','15','16','17','18','19','20','21','22']

    if (ordr == 3):
        if (LC == 'CI'):
            Lag_strain_list = ['01','08','23','32','10','11']
        if (LC == 'CII'):
            Lag_strain_list = ['01','08','23','32','10','11','12','09']
        if (LC == 'HI'):
            Lag_strain_list = ['01','26','04','03','17','30','08','02','10','14']
        if (LC == 'HII'):
            Lag_strain_list = ['01','26','04','03','17','30','08','02','10','14','12','31']
        if (LC == 'RI'):
            Lag_strain_list = ['01','08','04','02','05','10','11','26','09','03','17','34','33','35']
        if (LC == 'RII'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'TI'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'TII'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'O'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'M'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'N'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')

if (mthd == 'Stress'):
    if (ordr == 2):
        if (LC == 'CI' or \
            LC == 'CII'):
            Lag_strain_list = ['36']
        if (LC == 'HI' or \
            LC == 'HII'):
            Lag_strain_list = ['36','38']
        if (LC == 'RI' or \
            LC == 'RII'):
            Lag_strain_list = ['36','38']
        if (LC == 'TI' or \
            LC == 'TII'):
            Lag_strain_list = ['36','38']
        if (LC == 'O'):
            Lag_strain_list = ['36','38','40']
        if (LC == 'M'):
            Lag_strain_list = ['36','37','38','39','40']
        if (LC == 'N'):
            Lag_strain_list = ['36','37','38','39','40','41']

    if (ordr == 3):
        if (LC == 'CI'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'CII'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'HI'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'HII'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'RI'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'RII'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'TI'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'TII'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'O'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'M'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')
        if (LC == 'N'):
            sys.exit('\n.... Oops SORRY: Not implemented yet. \n')

#%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%#
#%!%!% ---------------------------------- Structures Maker --------------------------------- %!%!%#
#%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%#
fP   = open(dir_name + '_P.struct', 'r')
Plins= fP.readlines()
fP.close()

fdis = open('Distorted_Parameters', 'w')
cont1= 0
for i in Lag_strain_list:
    Ls_list= Ls_Dic[i]

    cont1  = cont1 + 1
    if (cont1 < 10):
        Dstn = 'Dst0'+str(cont1)
    else:
        Dstn = 'Dst' +str(cont1)

    os.mkdir(Dstn)
    os.chdir(Dstn)

    print>>fdis, Dstn+', Lagrangian strain = ' + Ls_str[i]

    cont2 = 0
    for s in range(-ptn, ptn+1):
        r = mdr*s/ptn
        if (s==0):
            if (mthd == 'Energy'): r = 0.0001
            if (mthd == 'Stress'): r = 0.00001

        Ls = zeros(6)
        for i in range(6):
            Ls[i] = Ls_list[i]
        Lv = r*Ls

        #--- Lagrangian strain to physical strain (eta = eps + 0.5*eps*esp) -----------------------
        eta_matrix      = zeros((3,3))

        eta_matrix[0,0] = Lv[0]
        eta_matrix[0,1] = Lv[5]/2.
        eta_matrix[0,2] = Lv[4]/2.
        
        eta_matrix[1,0] = Lv[5]/2.
        eta_matrix[1,1] = Lv[1]
        eta_matrix[1,2] = Lv[3]/2.

        eta_matrix[2,0] = Lv[4]/2.
        eta_matrix[2,1] = Lv[3]/2.
        eta_matrix[2,2] = Lv[2]

        norm       = 1.0
        eps_matrix = eta_matrix
        if (linalg.norm(eta_matrix) > 0.7):
            sys.exit('\n.... Oops ERROR: Too large deformation!\n') 

        while( norm > 1.e-10 ):
            x          = eta_matrix - dot(eps_matrix, eps_matrix)/2.
            norm       = linalg.norm(x - eps_matrix)      
            eps_matrix = x

        #--- Calculating the M_new matrix ---------------------------------------------------------
        i_matrix   = array([[1., 0., 0.],
                            [0., 1., 0.], 
                            [0., 0., 1.]])
        def_matrix = i_matrix + eps_matrix
        M_new      = dot(M_old, def_matrix)

#------ Calculating the distorted lattice parameters and angles -----------------------------------
        A1    = sqrt(M_new[0,0]**2. + M_new[0,1]**2. + M_new[0,2]**2.)
        A2    = sqrt(M_new[1,0]**2. + M_new[1,1]**2. + M_new[1,2]**2.)
        A3    = sqrt(M_new[2,0]**2. + M_new[2,1]**2. + M_new[2,2]**2.)

        ALPHA = degrees(acos((M_new[1,0]*M_new[2,0] +\
                              M_new[1,1]*M_new[2,1] +\
                              M_new[1,2]*M_new[2,2])/(A2*A3)))
        BETA  = degrees(acos((M_new[0,0]*M_new[2,0] +\
                              M_new[0,1]*M_new[2,1] +\
                              M_new[0,2]*M_new[2,2])/(A1*A3)))
        GAMMA = degrees(acos((M_new[0,0]*M_new[1,0] +\
                              M_new[0,1]*M_new[1,1] +\
                              M_new[0,2]*M_new[1,2])/(A1*A2)))

#--------------------------------------------------------------------------------------------------
        cont2 = cont2 + 1
        if (cont2 < 10):
            Dstn_cont2 = Dstn +'_0'+str(cont2)
        else:
            Dstn_cont2 = Dstn +'_' +str(cont2)

        print>>fdis, Dstn_cont2 + ',  eta = '+'%13.10f'%(r)+','+'%12.6f'%(A1)   \
                                                               +'%12.6f'%(A2)   \
                                                               +'%12.6f'%(A3)   \
                                                               +'%12.6f'%(ALPHA)\
                                                               +'%12.6f'%(BETA) \
                                                               +'%12.6f'%(GAMMA)

        os.mkdir(Dstn_cont2)
        os.chdir(Dstn_cont2)
        #--- Writing the structure file -----------------------------------------------------------
        fo = open(Dstn_cont2 + '.struct', 'w')

        Plins.pop(0)
        Plins.insert(0, Dstn_cont2+'\n')

        Plins.pop(3)
        Lattice_Parameters = '%10.6f'%(A1)   +'%10.6f'%(A2)  +'%10.6f'%(A3)\
                           + '%10.6f'%(ALPHA)+'%10.6f'%(BETA)+'%10.6f'%(GAMMA)
        Plins.insert(3, Lattice_Parameters+'\n')

        for i in range(len(Plins)):
            print>>fo, Plins[i],
        fo.close()
        #------------------------------------------------------------------------------------------
        os.chdir('../')
    os.chdir('../')
    print>>fdis
print>>fdis,'   Distorted parameters: END'
fdis.close()
os.system('mkdir Structures_WIEN2k')
os.system('cp -f Dst??/Dst??_??/Dst??_??.struct Structures_WIEN2k/')
os.system('mv -f '+ dir_name +'_P.struct Structures_WIEN2k/')
#--------------------------------------------------------------------------------------------------
