#!/usr/bin/env python
#%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%#
#%!%!% ----------------------------------- ElaStic_Setup ----------------------------------- %!%!%#
#%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%!%#
#
# AUTHOR:
# Rostam Golesorkhtabar
# r.golesorkhtabar@gmail.com
# 
# DATE: 
# Tue Jan 01 00:00:00 2013
#
# SYNTAX:
# python ElaStic_Setup.py
#        ElaStic_Setup
# 
# EXPLANATION:
# 
#__________________________________________________________________________________________________

import sys
import os

print("\
        \n +----------------------------------------------------------------+\
        \n ******************************************************************\
        \n |*                  WELCOME TO Elastic Code                     *|\
        \n |*              VERSION: 1.01   DATE: 2020/04/22                *|\
        \n |*****************************************************************\
        \n +----------------------------------------------------------------+ ")

print("\
\n     Which DFT code would you like to apply for the calculations? \
\n     exciting  ---------=>  1                                     \
\n     WIEN2k    ---------=>  2                                     \
\n     Quantum ESPRESSO --=>  3")

num = int(input(">>>> Please choose (1, 2, or 3): "))

if (num == 1):
    os.system("ElaStic_Setup_exciting")
elif (num == 2):
    os.system("ElaStic_Setup_WIEN2K")
elif (num == 3):
    os.system("ElaStic_Setup_ESPRESSO")
else:
    sys.exit("\n.... Oops ERROR: Choose 1, 2, or 3 \n")
